
CREATE TABLE t(a INT, b INT);
CREATE TABLE s(b INT, c INT);

INSERT INTO t VALUES (1,1);
INSERT INTO t VALUES (2,2);
INSERT INTO s VALUES (1,1);
INSERT INTO s VALUES (2,2);
CREATE VIEW v1(a,b,c) AS
  SELECT * FROM t NATURAL JOIN s;
CREATE VIEW v2(b,c) AS
  SELECT * FROM s WHERE c>2;
CREATE VIEW u(a,b) AS
  SELECT a,v1.b FROM v1 JOIN v2 ON a=v2.c;
